name: Build Trndi for Linux ARM64 (Qt6 Widgetset)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux-arm64-qt6:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up QEMU for ARM64 emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Cache Lazarus/FPC installation
      - name: Cache Lazarus/FPC ARM64
        id: cache-lazarus-arm64
        uses: actions/cache@v3
        with:
          path: ~/.cache/lazarus-arm64
          key: lazarus-fpc-linux-arm64-qt6-v2

      # 5. Download Lazarus 4.0 ARM64 .deb files and Qt6Pas
      - name: Download Lazarus 4.0 ARM64 .deb files and Qt6Pas
        run: |
          wget https://download.lazarus-ide.org/Lazarus%20Linux%20arm64%20DEB/Lazarus%204.0/lazarus-project_4.0.0-0_arm64.deb
          wget https://download.lazarus-ide.org/Lazarus%20Linux%20arm64%20DEB/Lazarus%204.0/fpc-laz_3.2.3-240813_arm64.deb
          wget https://download.lazarus-ide.org/Lazarus%20Linux%20arm64%20DEB/Lazarus%204.0/fpc-src_3.2.3-240813_arm64.deb
          wget https://github.com/davidbannon/libqt6pas/releases/download/v6.2.10/libqt6pas6_6.2.10-1_arm64.deb

      # 6. Create ARM64 build environment using Docker
      - name: Build in ARM64 environment
        run: |
          # Create simplified Dockerfile for ARM64 build environment
          cat > Dockerfile.arm64 << 'EOF'
          FROM arm64v8/ubuntu:22.04
          
          # Set environment variables
          ENV DEBIAN_FRONTEND=noninteractive
          ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          
          # Install base dependencies in stages to avoid QEMU issues
          RUN apt-get update && apt-get install -y \
              wget p7zip-full build-essential git cmake pkg-config \
              && rm -rf /var/lib/apt/lists/*
          
          # Install GUI libraries separately
          RUN apt-get update && apt-get install -y \
              libgtk2.0-dev libgtk2.0-0 \
              && rm -rf /var/lib/apt/lists/*
          
          # Install Qt6 with minimal packages to avoid QEMU crashes
          RUN apt-get update && apt-get install -y \
              qt6-base-dev qt6-tools-dev libqt6core6 libqt6gui6 libqt6widgets6 \
              && rm -rf /var/lib/apt/lists/*
          
          # Copy .deb files
          COPY *.deb /tmp/
          
          # Install Lazarus and FPC
          RUN cd /tmp && \
              echo "=== Installing FPC and Lazarus ===" && \
              (dpkg -i fpc-laz_3.2.3-240813_arm64.deb fpc-src_3.2.3-240813_arm64.deb lazarus-project_4.0.0-0_arm64.deb || true) && \
              apt-get update && apt-get install -f -y
          
          # Install Qt6Pas carefully
          RUN cd /tmp && \
              echo "=== Installing Qt6Pas ===" && \
              (dpkg -i libqt6pas6_6.2.10-1_arm64.deb || true) && \
              apt-get update && apt-get install -f -y && \
              (ldconfig || true)
          
          # Simple verification without causing QEMU crashes
          RUN echo "=== Basic Verification ===" && \
              which lazbuild && \
              which fpc && \
              which qmake6 && \
              echo "Verification completed"
          
          WORKDIR /workspace
          EOF
          
          # Build the ARM64 Docker image
          docker buildx build --platform linux/arm64 --load -f Dockerfile.arm64 -t trndi-arm64-builder .

      # 7. Cache static libraries
      - name: Restore Static Libraries Cache ARM64
        id: cache-static-arm64
        uses: actions/cache@v3
        with:
          path: ../static-arm64
          key: static-libraries-linux-arm64-qt6

      # 8. Download and Extract Static Libraries if not cached
      - name: Download and Extract Static Libraries ARM64
        if: steps.cache-static-arm64.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/synopse/mORMot2/releases/download/2.3.stable/mormot2static.7z
          mkdir -p ../static-arm64
          7z x mormot2static.7z -o../static-arm64 -y

      - name: Save Static Libraries Cache ARM64
        if: steps.cache-static-arm64.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ../static-arm64
          key: static-libraries-linux-arm64-qt6

      # 9. Copy static libraries to build folder
      - name: Copy Static Libraries ARM64
        run: |
          cp -r ../static-arm64/aarch64-linux/* . 2>/dev/null || \
          cp -r ../static-arm64/arm64-linux/* . 2>/dev/null || \
          echo 'No ARM64 static libs found to copy'

      # 10. Cache mORMot2 source
      - name: Restore mORMot2 Cache
        id: cache-mormot2-arm64
        uses: actions/cache@v3
        with:
          path: externals/mORMot2
          key: mormot2-repo-linux-arm64

      # 11. Clone mORMot2 Repository if needed
      - name: Clone mORMot2 Repository
        if: steps.cache-mormot2-arm64.outputs.cache-hit != 'true'
        run: |
          mkdir -p externals
          git clone https://github.com/synopse/mORMot2.git externals/mORMot2

      # 12. Build inside ARM64 container - simplified to avoid QEMU crashes
      - name: Build Trndi.lpr in ARM64 environment
        run: |
          docker run --rm --platform linux/arm64 \
            -v $(pwd):/workspace \
            -w /workspace \
            trndi-arm64-builder \
            bash -c "
              echo '=== ARM64 Build Environment Info ===' && \
              uname -m && \
              echo 'FPC version:' && fpc -iV && \
              echo 'Lazbuild version:' && lazbuild --version && \
              echo 'QMake version:' && qmake6 -version && \
              echo '' && \
              
              echo '=== Building mORMot2 Package ===' && \
              lazbuild externals/mORMot2/packages/lazarus/mormot2.lpk && \
              echo '' && \
              
              echo '=== Attempting Qt6 build ===' && \
              lazbuild \
                --widgetset=qt6 \
                --build-mode='No Ext (Release)' \
                --cpu=aarch64 \
                --os=linux \
                Trndi.lpr 2>&1 && \
              echo 'Qt6 build completed successfully!' && \
              WIDGETSET='Qt6' || {
                echo 'Qt6 build failed, using GTK2 fallback...' && \
                lazbuild \
                  --widgetset=gtk2 \
                  --build-mode='No Ext (Release)' \
                  --cpu=aarch64 \
                  --os=linux \
                  Trndi.lpr && \
                echo 'GTK2 build completed successfully!' && \
                WIDGETSET='GTK2'
              } && \
              
              echo '=== Build Results ===' && \
              echo \"Widgetset used: \$WIDGETSET\" && \
              ls -lh Trndi && \
              file Trndi
            "

      # 13. Create artifacts directory
      - name: Create artifacts directory
        run: |
          mkdir -p artifacts-arm64
          if [ -f "Trndi" ]; then
            cp Trndi artifacts-arm64/
          else
            echo "Trndi binary not found, searching..."
            find . -name "Trndi" -type f -executable 2>/dev/null | head -5
            exit 1
          fi

      # 14. Verify ARM64 binary
      - name: Verify ARM64 binary
        run: |
          if [ -f "artifacts-arm64/Trndi" ]; then
            echo "=== ARM64 Binary Information ==="
            file artifacts-arm64/Trndi
            ls -lh artifacts-arm64/Trndi
            echo "=== Widget Set Detection ==="
            strings artifacts-arm64/Trndi | grep -E "(qt|gtk|Qt6|GTK)" | head -5 || echo "Widget set not detected in strings"
          else
            echo "ARM64 binary not found!"
            exit 1
          fi

      # 15. Package artifact
      - name: Package ARM64 artifact
        run: |
          cd artifacts-arm64
          zip ../Trndi-developer-build-linux-qt6-arm64.zip Trndi
          cd ..

      # 16. Create Release
      - name: Create ARM64 Release
        uses: softprops/action-gh-release@v1
        with:
          files: Trndi-developer-build-linux-qt6-arm64.zip
          tag_name: v${{ github.run_number }}-linux-arm64
          name: Linux Qt6 ARM64 Build ${{ github.run_number }}
          body: |
            Linux ARM64 developer build from commit ${{ github.sha }} (Qt6 ARM64).
            
            **Architecture**: ARM64 (aarch64)
            **Widgetset**: Qt6 (with GTK2 fallback)
            **Platform**: Linux
            
            Built using QEMU emulation on GitHub Actions.
            Simplified build process to avoid QEMU segmentation faults.
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}