name: Build Trndi for macOS ARM64 (Alternative)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Command Line Developer Tools
        run: |
          sudo xcode-select --install || true
          sudo xcodebuild -license accept || true

      - name: Download and Install FPC
        run: |
          # Download FPC for ARM64
          curl -L -o fpc-installer.dmg "https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.2.2/fpc-3.2.2.intelarm64-macosx.dmg/download"
          
          # Mount the DMG
          hdiutil attach fpc-installer.dmg
          
          # Install FPC
          sudo installer -pkg /Volumes/fpc-3.2.2.intelarm64-macosx/fpc-3.2.2-intelarm64-macosx.pkg -target /
          
          # Unmount
          hdiutil detach /Volumes/fpc-3.2.2.intelarm64-macosx
          
          # Verify installation
          fpc -iV

      - name: Download and Install Lazarus
        run: |
          # Download Lazarus
          curl -L -o lazarus-installer.dmg "https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%202.2.4/Lazarus-2.2.4-0-x86_64-macosx.dmg/download"
          
          # Mount the DMG
          hdiutil attach lazarus-installer.dmg
          
          # Install Lazarus
          sudo cp -R "/Volumes/Lazarus-2.2.4-0-x86_64-macosx/Lazarus.app" /Applications/
          
          # Unmount
          hdiutil detach "/Volumes/Lazarus-2.2.4-0-x86_64-macosx"
          
          # Add to PATH
          echo "/Applications/Lazarus.app/Contents/MacOS" >> $GITHUB_PATH
          
          # Verify installation
          ls -la /Applications/Lazarus.app/Contents/MacOS/

      - name: Modify project file to remove mormot2
        run: |
          find . -name "*.lpi" -type f -exec sed -i '' '/<Item>.*<PackageName Value="mormot2"\/>/,/<\/Item>/d' {} \;
          echo "Removed mormot2 package references from project files"

      - name: Build Trndi
        run: |
          echo "Starting build process for Trndi..."
          
          # Using the full path to lazbuild
          LAZBUILD="/Applications/Lazarus.app/Contents/MacOS/lazbuild"
          
          # Find the main project file
          echo "Locating .lpi files:"
          MAIN_PROJECT=$(find . -name "*.lpi" -type f | head -1)
          echo "Found project file: $MAIN_PROJECT"
          
          # Build the project
          "$LAZBUILD" --build-mode="Release" --cpu=aarch64 --os=darwin --widgetset=cocoa "$MAIN_PROJECT"
          
          # Remove quarantine attribute
          find . -name "*.app" -exec xattr -drv com.apple.quarantine {} \;

      - name: Package application
        run: |
          # Find the built app
          APP_PATH=$(find . -name "*.app" -type d | head -1)
          
          if [ -n "$APP_PATH" ]; then
            # Create output directory
            mkdir -p ./dist
            cp -R "$APP_PATH" ./dist/
            
            # Create zip archive
            cd ./dist
            zip -r ../Trndi-macos-arm64.zip ./*
            cd ..
            echo "Application packaged successfully"
          else
            echo "No .app files found to package"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trndi-macOS-arm64
          path: ./Trndi-macos-arm64.zip
          retention-days: 7
        if: success()
