name: Build and Run Trndi.lpr with Lazarus 4.0 RC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Cache Lazarus Installation
      - name: Restore Lazarus Cache
        uses: actions/cache@v3
        with:
          path: C:\Lazarus
          key: lazarus-4.0rc2-installation

      # 3. Install Lazarus 4.0 RC2
      - name: Install Lazarus 4.0 RC2
        run: |
          if (!(Test-Path "C:\Lazarus\lazbuild.exe")) {
            Invoke-WebRequest -Uri "https://download.lazarus-ide.org/Lazarus%20Windows%2064%20bits/Lazarus%204.0RC2/lazarus-4.0RC2-fpc-3.2.2-win64.exe" -OutFile "lazarus-4.0RC2.exe"
            Start-Process -FilePath "lazarus-4.0RC2.exe" -ArgumentList "/VERYSILENT", "/DIR=C:\Lazarus" -Wait
          }

      # 4. Cache Static Libraries
      - name: Restore Static Cache
        uses: actions/cache@v3
        with:
          path: ../static
          key: static-libraries

      # 5. Download and Extract Static Libraries if not cached
      - name: Download and Extract Static Libraries
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://github.com/synopse/mORMot2/releases/download/2.3.stable/mormot2static.7z" -OutFile "mormot2static.7z"
          mkdir ..\static
          & "C:\Program Files\7-Zip\7z.exe" x "mormot2static.7z" -o"..\static" -y

      # 6. Cache mORMot2 Repository
      - name: Restore mORMot2 Cache
        uses: actions/cache@v3
        with:
          path: externals/mORMot2
          key: mormot2-latest

      # 7. Clone mORMot2
      - name: Clone mORMot2
        if: steps.cache.outputs.cache-hit != 'true'
        run: git clone https://github.com/synopse/mORMot2.git externals/mORMot2

      # 8. Build mORMot2 Package
      - name: Build mORMot2 Package
        run: |
          & "C:\Lazarus\lazbuild.exe" "externals\mORMot2\packages\lazarus\mormot2.lpk"

      # 9. Build Trndi.lpr
      - name: Build Trndi.lpr
        run: |
          & "C:\Lazarus\lazbuild.exe" --lazarusdir="C:\Lazarus" --build-mode="Extensions (Release)" --compiler-options="-Fu../static/x86_64-win64" "Trndi.lpr"

      # 10. Run Trndi.exe and capture the output
      - name: Run Trndi.exe
        run: |
          & ".\Trndi.exe" > output.txt
          type output.txt

      # 11. Upload the output as an artifact
      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: Trndi-output
          path: output.txt
