name: Build and Run Trndi.lpr with Lazarus 4.0 RC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Clone mORMot2 repository
      - name: Clone mORMot2
        run: git clone https://github.com/synopse/mORMot2.git externals/mORMot2

      # 3. Download and Install Lazarus 4.0 RC2
      - name: Download Lazarus 4.0 RC2
        run: curl -L -o lazarus-4.0RC2.exe https://download.lazarus-ide.org/Lazarus%20Windows%2064%20bits/Lazarus%204.0RC2/lazarus-4.0RC2-fpc-3.2.2-win64.exe

      - name: Install Lazarus 4.0 RC2
        run: start /wait lazarus-4.0RC2.exe /VERYSILENT /DIR="C:\Lazarus"

      # 4. Build Trndi.lpr
      - name: Build Trndi.lpr
        run: |
          "C:\Lazarus\lazbuild.exe" externals\mORMot2\packages\lazarus\mormot2.lpk
          "C:\Lazarus\lazbuild.exe" Trndi.lpr

      # 5. Run Trndi.exe and capture the output
      - name: Run Trndi.exe
        run: |
          Trndi.exe > output.txt
          type output.txt

      # 6. Upload the output as an artifact
      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: Trndi-output
          path: output.txt
